export const muscleData = {
  pecho: {
    name: 'Pecho',
    description: 'El pecho está compuesto principalmente por el músculo pectoral mayor y pectoral menor. Su función principal es empujar, acercar y rotar internamente los brazos. Es un grupo muscular clave en movimientos de fuerza como empujes horizontales e inclinados, y participa activamente en ejercicios como press y aperturas.',
    exercises: [
      {
        id: 'pecho-1',
        name: 'Press de Banca',
        description: 'Ejercicio de fuerza que trabaja principalmente el pecho (pectorales), junto con tríceps y hombros, consistente en empujar una barra o mancuernas desde el pecho hacia arriba mientras estás acostado en un banco.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://www.youtube.com/watch?v=TAH8RxOS0VI',
        thumbnailUrl: 'https://img.youtube.com/vi/TAH8RxOS0VI/hqdefault.jpg',
      },
      {
        id: 'pecho-2',
        name: 'Press de Banca Inclinado con Barra',
        description: 'Ejercicio de fuerza enfocado en la parte superior del pecho, donde se empuja una barra hacia arriba desde el pecho estando acostado en un banco inclinado, involucrando también hombros y tríceps.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/9eU0wzoORXM?si=aOrdGr4vwAXUsXws',
        thumbnailUrl: 'https://img.youtube.com/vi/9eU0wzoORXM/hqdefault.jpg',
      },
      {
        id: 'pecho-3',
        name: 'Press de Banca Inclinado con Mancuernas',
        description: 'Variante que trabaja principalmente el pecho superior, permitiendo mayor rango de movimiento y activación estabilizadora al empujar dos mancuernas desde un banco inclinado.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/kyyEx6Q6ASk?si=uKYjT10O4cgvcTxe',
        thumbnailUrl: 'https://img.youtube.com/vi/kyyEx6Q6ASk/hqdefault.jpg',
      },
      {
        id: 'pecho-4',
        name: 'Cruce en Poleas',
        description: 'Ejercicio de aislamiento que trabaja principalmente los pectorales. Consiste en llevar ambas poleas desde los costados hacia el frente del cuerpo, cruzando ligeramente las manos, para generar una contracción máxima del pecho durante todo el recorrido.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/fRIgvZWg2BI?si=TETHkuD4T-4udUNn',
        thumbnailUrl: 'https://img.youtube.com/vi/fRIgvZWg2BI/hqdefault.jpg',
      },
    ],
  },
  espalda: {
    name: 'Espalda',
    description: 'La espalda está compuesta por varios músculos, entre ellos el dorsal ancho, trapecio, romboides y erectores espinales. Su función principal es permitir los movimientos de tracción (jalones y remos), estabilizar la columna y mantener una postura adecuada. Es un grupo muscular fundamental para la fuerza, la estabilidad y el equilibrio corporal.',
    exercises: [
      {
        id: 'espalda-1',
        name: 'Jalón al pecho',
        description: 'Ejercicio de espalda que se realiza en polea alta, llevando la barra desde arriba hacia el pecho mediante la flexión de los codos y la retracción de las escápulas. Trabaja principalmente el dorsal ancho, junto con bíceps y músculos de la zona media de la espalda.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/EO9AmI-bu_0?si=CHq7H5CX0mlF43vT',
        thumbnailUrl: 'https://img.youtube.com/vi/EO9AmI-bu_0/hqdefault.jpg',
      },
      {
        id: 'espalda-2',
        name: 'Remo en polea baja',
        description: 'Ejercicio de espalda que se realiza sentado frente a una polea baja, llevando el agarre hacia el abdomen mediante la flexión de los codos y la retracción de las escápulas. Trabaja principalmente la zona media de la espalda (dorsales, romboides y trapecio), además de involucrar los bíceps.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/gfc5NDJrVOk?si=9j40tNl7XTWgYbYu',
        thumbnailUrl: 'https://img.youtube.com/vi/gfc5NDJrVOk/hqdefault.jpg',
      },
      {
        id: 'espalda-3',
        name: 'Peso muerto',
        description: 'Ejercicio compuesto de fuerza que consiste en levantar una barra desde el suelo hasta la altura de las caderas, extendiendo cadera y rodillas. Trabaja principalmente la cadena posterior: espalda baja (erectores espinales), glúteos e isquiotibiales, además de involucrar trapecios y antebrazos.',
        difficulty: 'advanced' as const,
        videoUrl: 'https://youtu.be/0XL4cZR2Ink?si=nOblrLo2rLZGiIfY',
        thumbnailUrl: 'https://img.youtube.com/vi/0XL4cZR2Ink/hqdefault.jpg',
      },
      {
        id: 'espalda-4',
        name: 'Remo con barra',
        description: 'Ejercicio compuesto para desarrollar grosor en la espalda. Se realiza inclinando el torso hacia adelante con la espalda recta y llevando la barra hacia el abdomen mediante la flexión de los codos y la retracción de las escápulas. Trabaja principalmente dorsales, romboides y trapecio, además de involucrar bíceps y zona lumbar como estabilizadores.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/OXH-ecu-Obw?si=YjkkbPNypS1ELMt3',
        thumbnailUrl: 'https://img.youtube.com/vi/OXH-ecu-Obw/hqdefault.jpg',
      },
    ],
  },
  hombros: {
    name: 'Hombros',
    description: 'Los hombros están formados principalmente por el músculo deltoides, que se divide en tres porciones: anterior, lateral y posterior. Su función es permitir la elevación, rotación y estabilización del brazo en múltiples direcciones. Son fundamentales en movimientos de empuje y tracción, además de aportar amplitud y estética al tren superior.',
    exercises: [
      {
        id: 'hombros-1',
        name: 'Press militar con barra',
        description: 'Ejercicio compuesto de hombros que consiste en empujar una barra desde la altura de los hombros hacia arriba hasta extender completamente los brazos. Trabaja principalmente el deltoide anterior y lateral, además de involucrar tríceps y core como estabilizadores.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/xmAsup6qwk0?si=h2d7ozjfFbhHG2lw',
        thumbnailUrl: 'https://img.youtube.com/vi/xmAsup6qwk0/hqdefault.jpg',
      },
      {
        id: 'hombros-2',
        name: 'Elevaciones frontales',
        description: 'Ejercicio de aislamiento para hombros que consiste en elevar una mancuerna, barra o disco al frente del cuerpo hasta la altura de los hombros, manteniendo los brazos casi extendidos. Trabaja principalmente el deltoide anterior.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/joO2vLGujcA?si=SxFg0Vwh7-U1RbnB',
        thumbnailUrl: 'https://img.youtube.com/vi/joO2vLGujcA/hqdefault.jpg',
      },
      {
        id: 'hombros-3',
        name: 'Elevaciones laterales con mancuernas',
        description: 'Ejercicio de aislamiento para hombros que consiste en elevar ambas mancuernas hacia los costados hasta la altura de los hombros, con una ligera flexión de codos. Trabaja principalmente el deltoide lateral, ayudando a dar mayor amplitud al hombro.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/hgLpdwMtEEs?si=zTOCVZ1xLCT2afEG',
        thumbnailUrl: 'https://img.youtube.com/vi/hgLpdwMtEEs/hqdefault.jpg',
      },
      {
        id: 'hombros-4',
        name: 'Face pull',
        description: 'Ejercicio de aislamiento que se realiza en polea alta con cuerda, tirando del agarre hacia el rostro con los codos elevados y abiertos. Trabaja principalmente el deltoide posterior, trapecio medio y romboides, ayudando a mejorar la postura y la estabilidad del hombro.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/X-xCQ1gh-kA?si=7dNoHTJ1gQm-GpRM',
        thumbnailUrl: 'https://img.youtube.com/vi/X-xCQ1gh-kA/hqdefault.jpg',
      },
    ],
  },
  biceps: {
    name: 'Bíceps',
    description: 'El bíceps es un músculo ubicado en la parte frontal del brazo, compuesto principalmente por dos cabezas (larga y corta). Su función principal es la flexión del codo y la supinación del antebrazo (girar la palma hacia arriba). Es fundamental en ejercicios de tracción y movimientos de curl.',
    exercises: [
      {
        id: 'biceps-1',
        name: 'Curl con barra agarre cerrado',
        description: 'Ejercicio de bíceps donde se sostiene la barra con las manos a una distancia menor al ancho de hombros. Este agarre enfatiza la cabeza larga del bíceps, ayudando a desarrollar mayor pico muscular.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/Vky1xC7PONk?si=tNIB-yogKuRlNcIO',
        thumbnailUrl: 'https://img.youtube.com/vi/Vky1xC7PONk/hqdefault.jpg',
      },
      {
        id: 'biceps-2',
        name: 'Curl inclinado con mancuernas',
        description: 'Se ejecuta sentado en un banco inclinado, dejando los brazos colgar hacia atrás. Esta posición estira la cabeza larga del bíceps, aumentando su activación.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/m2VZFlcJsaM?si=LIhVqOHjjlI7QQxC',
        thumbnailUrl: 'https://img.youtube.com/vi/m2VZFlcJsaM/hqdefault.jpg',
      },
      {
        id: 'biceps-3',
        name: 'Curl predicador (Scott)',
        description: 'Ejercicio de aislamiento para bíceps que se realiza apoyando los brazos en un banco predicador. Mantiene el brazo fijo, reduciendo el impulso y enfocando el trabajo en la cabeza corta del bíceps.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/Zb5YLtjEV0Y?si=7ssrF46qx4UgLYN3',
        thumbnailUrl: 'https://img.youtube.com/vi/Zb5YLtjEV0Y/hqdefault.jpg',
      },
      {
        id: 'biceps-4',
        name: 'Curl en polea alta',
        description: 'Ejercicio de aislamiento para bíceps que se realiza con las poleas ubicadas a la altura de los hombros o por encima. Con los brazos abiertos a los lados, se flexionan los codos llevando las manos hacia la cabeza, imitando la pose de “doble bíceps”.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/SykZPuLKj14?si=0eO2Oc7_zyJUk__a',
        thumbnailUrl: 'https://img.youtube.com/vi/SykZPuLKj14/hqdefault.jpg',
      },
    ],
  },
  triceps: {
    name: 'Tríceps',
    description: 'El tríceps es el músculo ubicado en la parte posterior del brazo y está compuesto por tres cabezas: larga, lateral y medial. Su función principal es la extensión del codo, siendo fundamental en movimientos de empuje como press de banca, fondos y extensiones. Es clave para el desarrollo del volumen y la fuerza del brazo',
    exercises: [
      {
        id: 'triceps-1',
        name: 'Press francés con barra',
        description: 'Ejercicio de aislamiento para tríceps que se realiza acostado en un banco, sosteniendo una barra con los brazos extendidos y flexionando los codos para llevarla hacia la frente o detrás de la cabeza. Trabaja principalmente la cabeza larga del tríceps',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/PTO862T8U7Y?si=PKOVF2wvObO5fbHM',
        thumbnailUrl: 'https://img.youtube.com/vi/PTO862T8U7Y/hqdefault.jpg',
      },
      {
        id: 'triceps-2',
        name: 'Extensión de tríceps en polea',
        description: 'Ejercicio de aislamiento que se realiza en polea alta, empujando el agarre hacia abajo mediante la extensión de los codos. Trabaja principalmente las cabezas lateral y medial del tríceps. Es importante mantener los codos pegados al cuerpo y controlar tanto la bajada como la subida para mantener la tensión constante',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/dRkTreltpnc?si=tjq-Y98q5m7HjvuR',
        thumbnailUrl: 'https://img.youtube.com/vi/dRkTreltpnc/hqdefault.jpg',
      },
      {
        id: 'triceps-3',
        name: 'Extensión por encima de la cabeza con mancuerna',
        description: 'Ejercicio de aislamiento para tríceps que se realiza sosteniendo una mancuerna por encima de la cabeza con ambos brazos (o uno solo) y flexionando los codos para bajarla detrás de la cabeza antes de extenderlos nuevamente. Trabaja especialmente la cabeza larga del tríceps debido a la posición elevada del brazo.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/fQ-KB40W3d8?si=_GfC9h02lLDB_VL_',
        thumbnailUrl: 'https://img.youtube.com/vi/fQ-KB40W3d8/hqdefault.jpg',
      },
      {
        id: 'triceps-4',
        name: 'Patada de tríceps',
        description: 'Ejercicio de aislamiento que se realiza inclinando el torso hacia adelante, manteniendo el brazo pegado al cuerpo y extendiendo el codo hacia atrás hasta estirarlo por completo. Trabaja principalmente la cabeza lateral del tríceps',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/eO0vfxnCcLk?si=V-qOJ9qIBM5V5C6_',
        thumbnailUrl: 'https://img.youtube.com/vi/eO0vfxnCcLk/hqdefault.jpg',
      },
    ],
  },
  abs: {
    name: 'Abdominales',
    description: 'Los abdominales son un grupo de músculos ubicados en la parte frontal y lateral del abdomen. Su función principal es estabilizar el torso, proteger los órganos internos y permitir movimientos como la flexión, rotación y estabilización de la columna. Además, cumplen un papel clave en la postura, el equilibrio y la transferencia de fuerza entre la parte superior e inferior del cuerpo.',
    exercises: [
      {
        id: 'abs-1',
        name: 'Crunch con cable en polea',
        description: 'El crunch con cable en polea es un ejercicio de abdomen que se realiza usando una polea alta con cuerda. Consiste en flexionar el torso hacia adelante contrayendo los abdominales mientras se tira del cable, manteniendo la cadera fija.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://www.youtube.com/watch?v=Xtngw8PFqYM',
        thumbnailUrl: 'https://img.youtube.com/vi/Xtngw8PFqYM/hqdefault.jpg',
      },
      {
        id: 'abs-2',
        name: 'Plancha abdominal',
        description: 'La plancha abdominal es un ejercicio isométrico que consiste en mantener el cuerpo recto y alineado mientras se apoya el peso sobre los antebrazos y las puntas de los pies. Este ejercicio trabaja principalmente el core, incluyendo el recto abdominal, el transverso abdominal y los oblicuos, además de activar músculos estabilizadores como los glúteos y la zona lumbar.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://www.youtube.com/watch?v=d0atctiI7Vw',
        thumbnailUrl: 'https://img.youtube.com/vi/d0atctiI7Vw/hqdefault.jpg',
      },
      {
        id: 'abs-3',
        name: 'Plancha Lateral',
        description: 'Es un ejercicio isométrico que consiste en mantener el cuerpo alineado de lado apoyando un antebrazo y el lateral del pie en el suelo, elevando la cadera para formar una línea recta desde la cabeza hasta los pies. Este ejercicio trabaja principalmente los oblicuos, además del core y músculos estabilizadores, ayudando a mejorar la estabilidad del tronco, el equilibrio y la fuerza del abdomen lateral.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://www.youtube.com/watch?v=45t3tTcRcKE',
        thumbnailUrl: 'https://img.youtube.com/vi/45t3tTcRcKE/hqdefault.jpg',
      },
    ],
  },
  cuadriceps: {
    name: 'Cuádriceps',
    description: 'El cuádriceps es el grupo muscular ubicado en la parte frontal del muslo y está compuesto por cuatro músculos: recto femoral, vasto lateral, vasto medial y vasto intermedio. Su función principal es la extensión de la rodilla y participa activamente en movimientos como sentadillas, estocadas y saltos. Es fundamental para la fuerza, estabilidad y potencia del tren inferior',
    exercises: [
      {
        id: 'cuadriceps-1',
        name: 'Sentadilla con barra',
        description: 'Ejercicio compuesto fundamental para el tren inferior que consiste en descender flexionando caderas y rodillas con una barra apoyada sobre los hombros, y luego extenderlas para volver a la posición inicial. Trabaja principalmente los cuádriceps, además de glúteos e isquiotibiales, y requiere activación del core para mantener la estabilidad.',
        difficulty: 'advanced' as const,
        videoUrl: 'https://youtu.be/qsAkuNORgmk?si=E6hntE8vhT79RV2m',
        thumbnailUrl: 'https://img.youtube.com/vi/qsAkuNORgmk/hqdefault.jpg',
      },
      {
        id: 'cuadriceps-2',
        name: 'Prensa de piernas',
        description: 'Ejercicio compuesto para el tren inferior que se realiza en máquina, empujando una plataforma con los pies mediante la extensión de rodillas y caderas. Trabaja principalmente los cuádriceps, aunque también involucra glúteos e isquiotibiales según la posición de los pies.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/bNsrqXUIJqc?si=0Sg1ERj80y6q84po',
        thumbnailUrl: 'https://img.youtube.com/vi/bNsrqXUIJqc/hqdefault.jpg',
      },
      {
        id: 'cuadriceps-3',
        name: 'Zancadas',
        description: 'Ejercicio compuesto del tren inferior que consiste en dar un paso hacia adelante (o hacia atrás) y descender flexionando ambas rodillas hasta formar aproximadamente un ángulo de 90°. Trabaja principalmente los cuádriceps y glúteos, además de mejorar el equilibrio y la estabilidad.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/FtNBlVNKrs0?si=6qzYSvpKpQCJF8TQ',
        thumbnailUrl: 'https://img.youtube.com/vi/FtNBlVNKrs0/hqdefault.jpg',
      },
      {
        id: 'cuadriceps-4',
        name: 'Extensión de piernas en máquina',
        description: 'Ejercicio de aislamiento para cuádriceps que se realiza sentado en una máquina, extendiendo las rodillas para elevar el peso desde una posición flexionada hasta estirar casi por completo las piernas. Trabaja de forma directa los cuatro músculos del cuádriceps.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/DI34ngDC8FU?si=t6Lii27NDvHvNUpr',
        thumbnailUrl: 'https://img.youtube.com/vi/DI34ngDC8FU/hqdefault.jpg',
      },
    ],
  },
  isquiotibiales: {
    name: 'Isquiotibiales',
    description: 'Los isquiotibiales son el grupo muscular ubicado en la parte posterior del muslo, compuesto por el bíceps femoral, semitendinoso y semimembranoso. Su función principal es la flexión de la rodilla y la extensión de la cadera. Son fundamentales para la potencia, la estabilidad de la rodilla y el rendimiento en movimientos como correr, saltar y realizar peso muerto',
    exercises: [
      {
        id: 'isquiotibiales-1',
        name: 'Peso muerto rumano',
        description: 'Ejercicio de fuerza enfocado en isquiotibiales y glúteos que consiste en bajar la barra manteniendo las piernas semi flexionadas y llevando la cadera hacia atrás. Prioriza el estiramiento controlado de la cadena posterior.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/99aPIw8XxRg?si=azNG0xVxOYDjtiGK',
        thumbnailUrl: 'https://img.youtube.com/vi/99aPIw8XxRg/hqdefault.jpg',
      },
      {
        id: 'isquiotibiales-2',
        name: 'Peso muerto convencional',
        description: 'Ejercicio compuesto de fuerza que consiste en levantar una barra desde el suelo hasta la posición erguida, extendiendo rodillas y caderas. Trabaja principalmente glúteos e isquiotibiales.',
        difficulty: 'advanced' as const,
        videoUrl: 'https://youtu.be/kancsOn7CJY?si=SQVN7jFp312IbZrW',
        thumbnailUrl: 'https://img.youtube.com/vi/kancsOn7CJY/hqdefault.jpg',
      },
      {
        id: 'isquiotibiales-3',
        name: 'Curl femoral sentado',
        description: 'Ejercicio de aislamiento para isquiotibiales que se realiza en máquina, flexionando las rodillas para llevar el rodillo hacia abajo. Permite un buen estiramiento debido a la posición de cadera flexionada.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/locj9zuXya0?si=y2I1FvoNLh6Z8poK',
        thumbnailUrl: 'https://img.youtube.com/vi/locj9zuXya0/hqdefault.jpg',
      },
      {
        id: 'isquiotibiales-4',
        name: 'Curl femoral acostado en máquina',
        description: 'Ejercicio de aislamiento que se realiza tumbado boca abajo, flexionando las rodillas para llevar el rodillo hacia los glúteos. Trabaja directamente la parte posterior del muslo.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/-jeW_ToaRB8?si=89raXmO9yw4PGTvr',
        thumbnailUrl: 'https://img.youtube.com/vi/-jeW_ToaRB8/hqdefault.jpg',
      },
    ],
  },
  gluteos: {
    name: 'Glúteos',
    description: 'Los glúteos están compuestos por tres músculos: glúteo mayor, medio y menor. Su función principal es la extensión, abducción y rotación de la cadera, además de estabilizar la pelvis durante la marcha y otros movimientos. Son fundamentales para la fuerza, la postura y la potencia en ejercicios como sentadillas, peso muerto y zancadas',
    exercises: [
      {
        id: 'gluteos-1',
        name: 'Hip Thrust',
        description: 'Ejercicio enfocado principalmente en el glúteo mayor que consiste en apoyar la parte alta de la espalda en un banco y empujar la cadera hacia arriba con una barra o peso sobre la pelvis. Es clave mantener el core activado y contraer los glúteos en la parte alta.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/lmUx6WAV-BQ?si=wN9jXkbt7nomxQU0',
        thumbnailUrl: 'https://img.youtube.com/vi/lmUx6WAV-BQ/hqdefault.jpg',
      },
      {
        id: 'gluteos-2',
        name: 'Peso muerto rumano',
        description: 'Ejercicio de fuerza enfocado en glúteos e isquiotibiales que consiste en descender la barra manteniendo las piernas semi flexionadas y llevando la cadera hacia atrás. Prioriza el estiramiento controlado de la cadena posterior.',
        difficulty: 'intermediate' as const,
        videoUrl: 'https://youtu.be/99aPIw8XxRg?si=9IhhL5LrQeOtY1bp',
        thumbnailUrl: 'https://img.youtube.com/vi/99aPIw8XxRg/hqdefault.jpg',
      },
      {
        id: 'gluteos-3',
        name: 'Sentadilla búlgara',
        description: 'Ejercicio unilateral que se realiza apoyando un pie en un banco detrás del cuerpo. Trabaja intensamente glúteos y cuádriceps, además de mejorar el equilibrio y la estabilidad.',
        difficulty: 'advanced' as const,
        videoUrl: 'https://youtu.be/6d6HlPWgAUs?si=5E8H1O9Vfk9h9rb8',
        thumbnailUrl: 'https://img.youtube.com/vi/6d6HlPWgAUs/hqdefault.jpg',
      },
      {
        id: 'gluteos-4',
        name: 'Patada lateral en polea',
        description: 'Ejercicio de aislamiento para glúteos que se realiza con una tobillera en polea baja, llevando la pierna hacia el costado. Trabaja principalmente el glúteo medio y menor.',
        difficulty: 'beginner' as const,
        videoUrl: 'https://youtu.be/pq6yI87oMFU?si=x1RKss5qQ-hWgM3i',
        thumbnailUrl: 'https://img.youtube.com/vi/pq6yI87oMFU/hqdefault.jpg',
      },
    ],
  },
  pantorrillas: {
    name: 'Pantorrillas',
    description: 'Músculos de la parte inferior de la pierna.',
    exercises: [
      {
        id: '12',
        name: 'Elevación de Talones',
        description: 'Ejercicio básico para pantorrillas',
        difficulty: 'beginner' as const,
        videoUrl: 'https://example.com/elevacion-talones.mp4',
        thumbnailUrl: 'https://via.placeholder.com/300x200',
      },
    ],
  },
};
